//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medical_center_galenos_desktop.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        public int BILL_ID { get; set; }
        public int SPECIALIST_ID { get; set; }
        public int PATIENT_ID { get; set; }
        public int SCHEDULE_ID { get; set; }
        public Nullable<int> PAYMENT_TYPE_ID { get; set; }
        public int STATE_MEDICAL_TIME_ID { get; set; }
        public Nullable<int> FORECAST_ID { get; set; }
        public System.DateTime BILL_MEDICAL_TIME { get; set; }
        public Nullable<int> BILL_COMMISSIONS { get; set; }
        public Nullable<int> BILL_SALARY { get; set; }
        public string BILL_STATUS { get; set; }
    
        public virtual SPECIALIST SPECIALIST { get; set; }
        public virtual PATIENT PATIENT { get; set; }
        public virtual SCHEDULE SCHEDULE { get; set; }
        public virtual PAYMENT_TYPE PAYMENT_TYPE { get; set; }
        public virtual STATE_MEDICAL_TIME STATE_MEDICAL_TIME { get; set; }
        public virtual FORECAST FORECAST { get; set; }
    }
}
