//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medical_center_galenos_desktop.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRANCH_OFFICE_CATEGORY
    {
        public int BRANCH_OFFICE_CATEGORY_ID { get; set; }
        public int BRANCH_OFFICE_ID { get; set; }
        public int CATEGORY_ID { get; set; }
    
        public virtual BRANCH_OFFICE BRANCH_OFFICE { get; set; }
        public virtual CATEGORY CATEGORY { get; set; }
    }
}
