//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medical_center_galenos_desktop.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORY
    {
        public CATEGORY()
        {
            this.BRANCH_OFFICE_CATEGORY = new HashSet<BRANCH_OFFICE_CATEGORY>();
            this.PERSONAL = new HashSet<PERSONAL>();
        }
    
        public int CATEGORY_ID { get; set; }
        public string CATEGORY_DESCRIPTION { get; set; }
        public string CATEGORY_STATUS { get; set; }
    
        public virtual ICollection<BRANCH_OFFICE_CATEGORY> BRANCH_OFFICE_CATEGORY { get; set; }
        public virtual ICollection<PERSONAL> PERSONAL { get; set; }
    }
}
