//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medical_center_galenos_desktop.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT_LOG
    {
        public int EVENT_LOG_ID { get; set; }
        public int USER_ID { get; set; }
        public string EVENT_LOG_DESCRIPTION { get; set; }
        public System.DateTime EVENT_LOG_DATE { get; set; }
        public short EVENT_LOG_STATUS_CODE { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
