//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medical_center_galenos_desktop.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXCEPTION_LOG
    {
        public int EXCEPTION_LOG_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string EXCEPTION_LOG_DESCRIPTION { get; set; }
        public System.DateTime EXCEPTION_LOG_DATE { get; set; }
        public short EXCEPTION_LOG_STATUS_CODE { get; set; }
        public string EXCEPTION_LOG_CONTROLLER { get; set; }
        public string EXCEPTION_LOG_METHOD { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
