//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medical_center_galenos_desktop.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENDER
    {
        public GENDER()
        {
            this.PATIENT = new HashSet<PATIENT>();
            this.PERSONAL = new HashSet<PERSONAL>();
            this.SPECIALIST = new HashSet<SPECIALIST>();
        }
    
        public int GENDER_ID { get; set; }
        public string GENDER_DESCRIPTION { get; set; }
        public string GENDER_STATUS { get; set; }
    
        public virtual ICollection<PATIENT> PATIENT { get; set; }
        public virtual ICollection<PERSONAL> PERSONAL { get; set; }
        public virtual ICollection<SPECIALIST> SPECIALIST { get; set; }
    }
}
