//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medical_center_galenos_desktop.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAL
    {
        public PERSONAL()
        {
            this.USER = new HashSet<USER>();
        }
    
        public int PERSONAL_ID { get; set; }
        public int CATEGORY_ID { get; set; }
        public int BRANCH_OFFICE_ID { get; set; }
        public int GENDER_ID { get; set; }
        public string PERSONAL_RUN { get; set; }
        public string PERSONAL_FIRST_NAME { get; set; }
        public string PERSONAL_SECOND_NAME { get; set; }
        public string PERSONAL_SURNAME { get; set; }
        public string PERSONAL_SECOND_SURNAME { get; set; }
        public string PERSONAL_FULL_NAME { get; set; }
        public System.DateTime PERSONAL_BIRTHDATE { get; set; }
        public string PERSONAL_EMAIL { get; set; }
        public string PERSONAL_STATUS { get; set; }
    
        public virtual BRANCH_OFFICE BRANCH_OFFICE { get; set; }
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual GENDER GENDER { get; set; }
        public virtual ICollection<USER> USER { get; set; }
    }
}
