//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medical_center_galenos_desktop.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFILE_ROLE
    {
        public int PROFILE_ROLE_ID { get; set; }
        public int PROFILE_ID { get; set; }
        public int ROLE_ID { get; set; }
    
        public virtual PROFILE PROFILE { get; set; }
        public virtual ROLE ROLE { get; set; }
    }
}
