//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medical_center_galenos_desktop.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPECIALTY
    {
        public SPECIALTY()
        {
            this.BRANCH_OFFICE_SPECIALTY = new HashSet<BRANCH_OFFICE_SPECIALTY>();
            this.SPECIALIST = new HashSet<SPECIALIST>();
        }
    
        public int SPECIALTY_ID { get; set; }
        public string SPECIALTY_DESCRIPTION { get; set; }
        public int SPECIALTY_AMOUNT { get; set; }
        public string SPECIALTY_STATUS { get; set; }
    
        public virtual ICollection<BRANCH_OFFICE_SPECIALTY> BRANCH_OFFICE_SPECIALTY { get; set; }
        public virtual ICollection<SPECIALIST> SPECIALIST { get; set; }
    }
}
